### PR TITLE
Init setup core-image-aap

### PR DESCRIPTION
**Pull request by phongt**
- Add git submodules poky, meta-virtualization dependcies
layers with master branch.
- meta-aap: new layer for Autosar Adaptive Platform
  + Instruction distro alsterwasser with linux-yocto-rt as default
  + core-images-aap with docker-ce, libstdc++, ssh, full-cmdline packages
  + core-images-aap-dev = core-images-aap + dev packages
- templateconf: sample template of local.conf, bblayers.conf

### CODE REVIEW

**Comment by phongt** [comment]
depend on container on https://github.com/UmlautSoftwareDevelopmentAccount/AUTOSAR-Adaptive/pull/40

**Comment by bburda** [comment]
```bash
dev@3ecb22baff32:~/workspace$ source poky/oe-init-build-env
You had no conf/local.conf file. This configuration file has therefore been
created for you with some default values. You may wish to edit it to, for
example, select a different MACHINE (target hardware). See conf/local.conf
for more information as common configuration options are commented.

You had no conf/bblayers.conf file. This configuration file has therefore been
created for you with some default values. To add additional metadata layers
into your configuration please add entries to conf/bblayers.conf.

The Yocto Project has extensive documentation about OE including a reference
manual which can be found at:
    http://yoctoproject.org/documentation

For more information about OpenEmbedded see their website:
    http://www.openembedded.org/


### Shell environment set up for builds. ###

You can now run 'bitbake <target>'

Common targets are:
    core-image-aap
    core-image-aap-dev
You can also run generated qemu images with a command like 'runqemu qemux86'

Other commonly useful commands are:
 - 'devtool' and 'recipetool' handle common recipe tasks
 - 'bitbake-layers' handles common layer tasks
 - 'oe-pkgdata-util' handles common target package tasks
dev@3ecb22baff32:~/workspace/build$ bitbake core-image-aap-dev
Loading cache: 100% |                                                                                                                                           | ETA:  --:--:--
Loaded 0 entries from dependency cache.
Parsing recipes: 100% |##########################################################################################################################################| Time: 0:01:19
Parsing of 2274 .bb files complete (0 cached, 2274 parsed). 3457 targets, 85 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.47.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-20.04"
TARGET_SYS           = "x86_64-poky-linux"
MACHINE              = "qemux86-64"
DISTRO               = "alsterwasser"
DISTRO_VERSION       = "1.0.0"
TUNE_FEATURES        = "m64 core2"
TARGET_FPU           = ""
meta                 
meta-poky            
meta-yocto-bsp       = "HEAD:259d2e35e7ba3cbd496d6383e58cfdc22b267f0e"
meta-oe              
meta-python          
meta-filesystems     
meta-networking      = "HEAD:81ee0b68fa32bcd60e1226f612ec63b1e672f263"
meta-virtualization  = "HEAD:97e83f3f3b55ef2997b85c52cc8b1cd9c5abde0c"
meta-aap             = "alsterwasser:119a71005af794f022c3a110e5593db96c3f6027"

NOTE: Fetching uninative binary shim from http://downloads.yoctoproject.org/releases/uninative/2.8/x86_64-nativesdk-libc.tar.xz;sha256sum=a09922172c3a439105e0ae6b943daad2d83505b17da0aba97961ff433b8c21ab
Initialising tasks: 100% |#######################################################################################################################################| Time: 0:00:06
Sstate summary: Wanted 2907 Found 0 Missed 2907 Current 0 (0% match, 0% complete)
NOTE: Executing Tasks
NOTE: Tasks Summary: Attempted 7227 tasks of which 1 didn't need to be rerun and all succeeded.
```

**Comment by bburda** [comment]
@phongt the image is building, I will check does build image is running on the qemu/docker container (it should) and I think, that you can set the status to `Ready for review` :)

**Comment by phongt** [comment]
> Looks good, but could you add some comments with OperatingSystemInterface Requirements, to mark which dependency or line of configuration fulfills which requirement?

Okay, add the descriptions in d30ef5b

**Pull request merged**
